//
// Created by Worker on 24.12.2023.
//

#ifndef ADS_STRUCTURES_SINGLELINKEDLINEARLISTCYCLED_H
#define ADS_STRUCTURES_SINGLELINKEDLINEARLISTCYCLED_H

#endif //ADS_STRUCTURES_SINGLELINKEDLINEARLISTCYCLED_H
